name: OpMon Build and Deploy
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    permissions:
      contents: read
      deployments: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.8
    - name: restore_cache
      uses: actions/cache@v3.3.2
      with:
        key: python-packages-v1-{{ .Branch }}-{{ checksum "requirements.in" }}-{{ checksum "requirements.txt" }}
        path: venv/
        restore-keys: |-
          python-packages-v1-{{ .Branch }}-{{ checksum "requirements.in" }}-{{ checksum "requirements.txt" }}
          python-packages-v1-{{ .Branch }}-{{ checksum "requirements.in" }}-
          python-packages-v1-{{ .Branch }}-
          python-packages-v1-
    - name: Build
      run: |-
        python3.10 -m venv venv/
        venv/bin/pip install --progress-bar off --upgrade -r requirements.txt
    - name: PyTest
      run: venv/bin/pytest --black --pydocstyle --ignore=opmon/tests/integration/
    - name: isort
      run: venv/bin/isort --check opmon
    - name: flake8
      run: venv/bin/flake8 opmon
    - name: Mypy
      run: venv/bin/mypy opmon
    - name: Build the Docker image
      if: github.ref == 'refs/heads/main'
      run: docker build . -t opmon
    - name: Push the Docker image to GAR
      if: github.ref == 'refs/heads/main'
      uses: mozilla-it/deploy-actions/docker-push@v3.11.1
      with:
        project_id: moz-fx-data-experiments
        local_image: opmon
        image_repo_host: gcr.io
        image_repo_path: moz-fx-data-experiments/opmon
        workload_identity_pool_project_number: ${{ vars.GCPV2_WORKLOAD_IDENTITY_POOL_PROJECT_NUMBER }}
        
